server:
  port: 8010

spring:
  application:
    name: APIGayeWay-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://192.168.10.130:8070/
          predicates:
            - Path=/gateWay/**

        - id: demo-service
          uri: http://192.168.10.130:8030/
          predicates:
            - Path=/demo/**

        - id: elasticsearch
          uri: http://192.168.10.125:9200/
          predicates:
            - Path=/demo/**
